/* Generated By:JavaCC: Do not edit this line. ColchitaConstants.java */
package foo;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ColchitaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int RETAZO1 = 1;
  /** RegularExpression Id. */
  int RETAZO2 = 2;
  /** RegularExpression Id. */
  int CONSTANT = 3;
  /** RegularExpression Id. */
  int DIGITO = 4;
  /** RegularExpression Id. */
  int GIRAR = 5;
  /** RegularExpression Id. */
  int COSER = 6;
  /** RegularExpression Id. */
  int LPAREN = 7;
  /** RegularExpression Id. */
  int RPAREN = 8;
  /** RegularExpression Id. */
  int COMA = 9;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"retazo1\"",
    "\"retazo2\"",
    "<CONSTANT>",
    "<DIGITO>",
    "\"girar\"",
    "\"coser\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
  };

}
