/* Generated By:JJTree: Do not edit this line. ASTCoser.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ar.edu.ub.colchita.modelo.javacc;

public
class ASTCoser extends SimpleNode {
  public ASTCoser(int id) {
    super(id);
  }

  public ASTCoser(Colchita p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ColchitaVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0426e9418ed8d1e8a1a07f4f276d61be (do not edit this line) */
