/* Generated By:JJTree: Do not edit this line. ASTRetazo.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ar.edu.ub.colchita.modelo.javacc;

public
class ASTRetazo extends SimpleNode {
  public ASTRetazo(int id) {
    super(id);
  }

  public ASTRetazo(Colchita p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ColchitaVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f978c4f37403b2baa831bf1b9e2fe2f3 (do not edit this line) */
