/* Generated By:JJTree&JavaCC: Do not edit this line. ColchitaConstants.java */
package ar.edu.ub.colchita.modelo.javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ColchitaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int RETAZO1 = 1;
  /** RegularExpression Id. */
  int RETAZO2 = 2;
  /** RegularExpression Id. */
  int GIRAR = 3;
  /** RegularExpression Id. */
  int COSER = 4;
  /** RegularExpression Id. */
  int LPAREN = 5;
  /** RegularExpression Id. */
  int RPAREN = 6;
  /** RegularExpression Id. */
  int COMA = 7;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"retazo1\"",
    "\"retazo2\"",
    "\"girar\"",
    "\"coser\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
  };

}
