/* Generated By:JavaCC: Do not edit this line. ColchitaVisitor.java Version 5.0 */
package ar.edu.ub.colchita.modelo.javacc;

public interface ColchitaVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTPrincipal node, Object data);
  public Object visit(ASTRetazo node, Object data);
  public Object visit(ASTGirar node, Object data);
  public Object visit(ASTCoser node, Object data);
}
/* JavaCC - OriginalChecksum=f922214c05839c080a040c22354ae03e (do not edit this line) */
