/* Generated By:JavaCC: Do not edit this line. ColchitaTreeConstants.java Version 5.0 */
package ar.edu.ub.colchita.modelo.javacc;

public interface ColchitaTreeConstants
{
  public int JJTPRINCIPAL = 0;
  public int JJTVOID = 1;
  public int JJTRETAZO = 2;
  public int JJTGIRAR = 3;
  public int JJTCOSER = 4;


  public String[] jjtNodeName = {
    "Principal",
    "void",
    "Retazo",
    "Girar",
    "Coser",
  };
}
/* JavaCC - OriginalChecksum=71f404df11dd73e9af95c6c2b4937d7f (do not edit this line) */
